#!/usr/bin/env bash
# gen-statectl-validators.sh — regenerate the three closed-enum validator function
# bodies inside statectl.sh from the authoritative tables/prose in state-schema.md.
#
# Output: the complete rewritten statectl.sh on stdout. Never edits in place.
#
# Usage (developer step, not invoked at runtime):
#   bash .claude/skills/run/tools/gen-statectl-validators.sh > statectl.sh.new \
#     && mv statectl.sh.new .claude/skills/run/statectl.sh
#
# Verified by statectl-selftest.sh case (r1+r5): the committed statectl.sh must
# byte-match a fresh regeneration. Drift between this script and state-schema.md
# fails that case.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SCHEMA="$SKILL_DIR/state-schema.md"
STATECTL="$SKILL_DIR/statectl.sh"

[[ -f "$SCHEMA" ]] || { echo "[gen] state-schema.md not found at $SCHEMA" >&2; exit 2; }
[[ -f "$STATECTL" ]] || { echo "[gen] statectl.sh not found at $STATECTL" >&2; exit 2; }

# ---------------------------------------------------------------- parsers ------

# Parse failureContext.reason values from the markdown table at
# `#### \`failureContext.reason\` index`. Each row's first column is a
# backticked code token; emit the bare value, one per line.
parse_failure_reasons() {
  awk '
    /^#### `failureContext.reason` index/ { in_section = 1; next }
    in_section && /^#### / { in_section = 0 }
    in_section && /^### / { in_section = 0 }
    in_section && /^## / { in_section = 0 }
    in_section && /^\| `/ {
      line = $0
      sub(/^\| `/, "", line)
      sub(/`.*$/, "", line)
      if (line != "" && line != "Reason") print line
    }
  ' "$SCHEMA"
}

# Parse deviations[].kind values from the prose line:
#   `deviations[].kind` is one of `"v1" | "v2" | ...`. ...
# Strategy: find the first matching line, then extract the second backtick-
# delimited segment (the values clause). Inside that clause, split on `|` and
# strip surrounding quotes/whitespace.
parse_deviation_kinds() {
  awk '
    /`deviations\[\]\.kind` is one of `/ {
      line = $0
      # Strip everything up to and including the first backtick after "one of ".
      sub(/^.*`deviations\[\]\.kind` is one of `/, "", line)
      # Now line starts with: "v1" | "v2" | ... "vN"`. ...
      # Drop the closing backtick and anything after.
      sub(/`.*$/, "", line)
      # Split on |, strip whitespace and quotes from each part.
      n = split(line, parts, /[[:space:]]*\|[[:space:]]*/)
      for (i = 1; i <= n; i++) {
        gsub(/^"|"$/, "", parts[i])
        if (parts[i] != "") print parts[i]
      }
      exit
    }
  ' "$SCHEMA"
}

# Parse stage-comment marker values from the markdown table at
# `#### Stage-comment markers`. Same shape as parse_failure_reasons: each row's
# first column is a backticked code token; emit the bare value, one per line.
# The anchor heading is level-4 (####) to mirror the reason index exactly, so
# the section-exit guards are identical.
parse_stage_markers() {
  awk '
    /^#### Stage-comment markers/ { in_section = 1; next }
    in_section && /^#### / { in_section = 0 }
    in_section && /^### / { in_section = 0 }
    in_section && /^## / { in_section = 0 }
    in_section && /^\| `/ {
      line = $0
      sub(/^\| `/, "", line)
      sub(/`.*$/, "", line)
      if (line != "" && line != "Marker") print line
    }
  ' "$SCHEMA"
}

# ---------------------------------------------------------------- builders ----

# Build the generated region for one validator function. Args:
#   $1 = function name (e.g. valid_failure_reason)
#   $2..$N = enum values (one per arg)
build_region() {
  local fn_name="$1"; shift
  local -a values=("$@")
  local count="${#values[@]}"

  if [[ "$count" -lt 1 ]]; then
    echo "[gen] no values parsed for $fn_name — aborting" >&2
    exit 3
  fi

  printf '# Generated by .claude/skills/run/tools/gen-statectl-validators.sh from state-schema.md\n'
  printf '# Do not hand-edit. Regenerate: bash .claude/skills/run/tools/gen-statectl-validators.sh > statectl.sh.new && mv statectl.sh.new statectl.sh\n'
  printf '%s() {\n' "$fn_name"
  # shellcheck disable=SC2016 # emitting literal shell source, $1 must not expand here
  printf '  case "$1" in\n'
  local i
  for (( i = 0; i < count; i++ )); do
    if (( i == 0 )); then
      # First value: no leading "|", trailing " \" if not last.
      if (( count == 1 )); then
        printf '    %s) return 0 ;;\n' "${values[0]}"
      else
        printf '    %s \\\n' "${values[0]}"
      fi
    elif (( i == count - 1 )); then
      printf '    |%s) return 0 ;;\n' "${values[i]}"
    else
      printf '    |%s \\\n' "${values[i]}"
    fi
  done
  printf '    *) return 1 ;;\n'
  printf '  esac\n'
  printf '}\n'
}

# ---------------------------------------------------------------- splicer -----

# Read values into arrays. while-read (not mapfile) — macOS ships bash 3.2 as
# /bin/bash and this script must run there (the selftest drift-check invokes it).
REASONS=()
while IFS= read -r v; do REASONS+=("$v"); done < <(parse_failure_reasons)
KINDS=()
while IFS= read -r v; do KINDS+=("$v"); done < <(parse_deviation_kinds)
MARKERS=()
while IFS= read -r v; do MARKERS+=("$v"); done < <(parse_stage_markers)

if (( ${#REASONS[@]} < 1 )); then
  echo "[gen] parsed zero failureContext.reason values from $SCHEMA — table format may have changed" >&2
  exit 4
fi
if (( ${#KINDS[@]} < 1 )); then
  echo "[gen] parsed zero deviations[].kind values from $SCHEMA — prose anchor may have changed" >&2
  exit 4
fi
if (( ${#MARKERS[@]} < 1 )); then
  echo "[gen] parsed zero stage-comment marker values from $SCHEMA — table format may have changed" >&2
  exit 4
fi

REASON_BODY="$(build_region valid_failure_reason "${REASONS[@]}")"
KIND_BODY="$(build_region valid_deviation_kind "${KINDS[@]}")"
MARKER_BODY="$(build_region valid_stage_marker "${MARKERS[@]}")"

# Splice all three regions into statectl.sh. Pure-bash state machine over the file:
# when an opening sentinel is matched, emit the matching new body and skip
# subsequent lines until the matching closing sentinel. (Passing multi-line
# strings to awk -v is non-portable across BSD/GNU awk, so this is bash.)
skip=""
while IFS= read -r line || [[ -n "$line" ]]; do
  case "$line" in
    "# >>> generated: valid_failure_reason >>>")
      printf '%s\n' "$line"
      printf '%s\n' "$REASON_BODY"
      skip="valid_failure_reason"
      continue
      ;;
    "# <<< generated: valid_failure_reason <<<")
      if [[ "$skip" == "valid_failure_reason" ]]; then
        printf '%s\n' "$line"
        skip=""
        continue
      fi
      ;;
    "# >>> generated: valid_deviation_kind >>>")
      printf '%s\n' "$line"
      printf '%s\n' "$KIND_BODY"
      skip="valid_deviation_kind"
      continue
      ;;
    "# <<< generated: valid_deviation_kind <<<")
      if [[ "$skip" == "valid_deviation_kind" ]]; then
        printf '%s\n' "$line"
        skip=""
        continue
      fi
      ;;
    "# >>> generated: valid_stage_marker >>>")
      printf '%s\n' "$line"
      printf '%s\n' "$MARKER_BODY"
      skip="valid_stage_marker"
      continue
      ;;
    "# <<< generated: valid_stage_marker <<<")
      if [[ "$skip" == "valid_stage_marker" ]]; then
        printf '%s\n' "$line"
        skip=""
        continue
      fi
      ;;
  esac
  if [[ -z "$skip" ]]; then
    printf '%s\n' "$line"
  fi
done < "$STATECTL"

if [[ -n "$skip" ]]; then
  echo "[gen] unclosed sentinel for $skip in statectl.sh — output may be incomplete" >&2
  exit 5
fi
